### ISSUE TITLE
Add its own Extensions settings

### ISSUE THREAD

**Issue by mihaijoldis** [easydigitaldownloads/edd-license-free-download#13]
At the moment a new "Main" tab is created in the main Extensions page. We should add its own proper tab in there.

**Comment by robincornett** [comment]
@mihaijoldis can you try the release/1.0.1 branch, please? I think we fixed this in #2 and have just a couple more items to resolve for that release.

**Comment by mihaijoldis** [comment]
@robincornett yeah i'm going to close this. i did the same thing in the other issue #14 but on that one i edited my message but there's still one issue is spotted.
