### ISSUE TITLE
Doesn't appear to be functioning with latest version of SL

### ISSUE THREAD

**Issue by nutsandbolts** [easydigitaldownloads/edd-license-free-download#6]
When a product is configured to be free and you enter the appropriate license key, you get 
the "The license key isn't allowed to download this product for free. Sorry." message even when configured correctly.

I get the following on the single product view when I try to submit a correct license key:

```Notice: Trying to get property 'status' of non-object in /home/263004.cloudwaysapps.com/kpkfkjvvfs/public_html/wp-content/plugins/EDD-Software-Licensing/edd-software-licenses.php on line 1961```

Customer reported the same thing here: https://secure.helpscout.net/conversation/1017430973/138202?folderId=180499

**Comment by dgoldak** [comment]
Another report of this issue:
https://secure.helpscout.net/conversation/1137140711/150891?folderId=1847242
